# Generated by Django 5.2 on 2025-04-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_is_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cashback',
            field=models.PositiveIntegerField(default=0, verbose_name='Кэшбэк (₽)'),
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('preorder', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Наличие'),
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/gallery/', verbose_name='Фото книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Фото книги',
                'verbose_name_plural': 'Галерея книг',
            },
        ),
    ]
